const vocabulario = {
  verbos: [
        { palabraSue: "Äta", palabraEsp: "Comer" },
        { palabraSue: "Dricka", palabraEsp: "Beber" },
        { palabraSue: "Skriva", palabraEsp: "Escribir" },
        { palabraSue: "Läsa", palabraEsp: "Leer" },
        { palabraSue: "Gå", palabraEsp: "Ir" },
        { palabraSue: "Köra", palabraEsp: "Conducir" },
        { palabraSue: "Sova", palabraEsp: "Dormir" },
        { palabraSue: "Se", palabraEsp: "Ver" },
        { palabraSue: "Höra", palabraEsp: "Escuchar" },
        { palabraSue: "Tala", palabraEsp: "Hablar" },
        { palabraSue: "Arbeta", palabraEsp: "Trabajar" },
        { palabraSue: "Springa", palabraEsp: "Correr" },
        { palabraSue: "Lära", palabraEsp: "Aprender" },
        { palabraSue: "Veta", palabraEsp: "Saber" },
        { palabraSue: "Måla", palabraEsp: "Pintar" },
        { palabraSue: "Sitta", palabraEsp: "Sentarse" },
        { palabraSue: "Stå", palabraEsp: "Estar de pie" },
        { palabraSue: "Laga", palabraEsp: "Cocinar" },
        { palabraSue: "Kasta", palabraEsp: "Lanzar" },
        { palabraSue: "Vänta", palabraEsp: "Esperar" },
        { palabraSue: "Få", palabraEsp: "Recibir" },
        { palabraSue: "Ge", palabraEsp: "Dar" },
        { palabraSue: "Föra", palabraEsp: "Llevar" },
        { palabraSue: "Bära", palabraEsp: "Cargar" },
        { palabraSue: "Hjälpa", palabraEsp: "Ayudar" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Skratta", palabraEsp: "Reír" },
        { palabraSue: "Gråta", palabraEsp: "Llorar" },
        { palabraSue: "Skriva", palabraEsp: "Escribir" },
        { palabraSue: "Titta", palabraEsp: "Mirar" },
        { palabraSue: "Växa", palabraEsp: "Crecer" },
        { palabraSue: "Träffa", palabraEsp: "Encontrarse con" },
        { palabraSue: "Besöka", palabraEsp: "Visitar" },
        { palabraSue: "Stänga", palabraEsp: "Cerrar" },
        { palabraSue: "Öppna", palabraEsp: "Abrir" },
        { palabraSue: "Kasta", palabraEsp: "Tirar" },
        { palabraSue: "Möta", palabraEsp: "Encontrar" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Höra", palabraEsp: "Oír" },
        { palabraSue: "Följa", palabraEsp: "Seguir" },
        { palabraSue: "Skrika", palabraEsp: "Gritar" },
        { palabraSue: "Ringa", palabraEsp: "Llamar" },
        { palabraSue: "Vinna", palabraEsp: "Ganar" },
        { palabraSue: "Förlora", palabraEsp: "Perder" },
        { palabraSue: "Känna", palabraEsp: "Conocer" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Vara", palabraEsp: "Ser/Estar" },
        { palabraSue: "Tycka", palabraEsp: "Pensar" },
        { palabraSue: "Hålla", palabraEsp: "Mantener" },
        { palabraSue: "Dela", palabraEsp: "Compartir" },
        { palabraSue: "Låna", palabraEsp: "Prestar" },
        { palabraSue: "Sluta", palabraEsp: "Terminar" },
        { palabraSue: "Börja", palabraEsp: "Empezar" },
        { palabraSue: "Laga", palabraEsp: "Arreglar" },
        { palabraSue: "Skriva", palabraEsp: "Escribir" },
        { palabraSue: "Göra", palabraEsp: "Hacer" },
        { palabraSue: "Bo", palabraEsp: "Vivir" },
        { palabraSue: "Kasta", palabraEsp: "Tirar" },
        { palabraSue: "Betala", palabraEsp: "Pagar" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Föreställa", palabraEsp: "Imaginar" },
        { palabraSue: "Förstå", palabraEsp: "Entender" },
        { palabraSue: "Berätta", palabraEsp: "Contar" },
        { palabraSue: "Fråga", palabraEsp: "Preguntar" },
        { palabraSue: "Föreslå", palabraEsp: "Sugerir" },
        { palabraSue: "Förena", palabraEsp: "Unir" },
        { palabraSue: "Lämna", palabraEsp: "Dejar" },
        { palabraSue: "Gå", palabraEsp: "Ir" },
        { palabraSue: "Använda", palabraEsp: "Usar" },
        { palabraSue: "Be", palabraEsp: "Pedir" },
        { palabraSue: "Koppla", palabraEsp: "Conectar" },
        { palabraSue: "Skriva", palabraEsp: "Escribir" },
        { palabraSue: "Veta", palabraEsp: "Saber" },
        { palabraSue: "Vara", palabraEsp: "Ser" },
        { palabraSue: "Möta", palabraEsp: "Encontrar" },
        { palabraSue: "Läsa", palabraEsp: "Leer" },
        { palabraSue: "Hör", palabraEsp: "Escuchar" },
        { palabraSue: "Berätta", palabraEsp: "Contar" },
        { palabraSue: "Slå", palabraEsp: "Golpear" },
        { palabraSue: "Stötta", palabraEsp: "Apoyar" },
        { palabraSue: "Kasta", palabraEsp: "Tirar" },
        { palabraSue: "Förstå", palabraEsp: "Comprender" },
        { palabraSue: "Visa", palabraEsp: "Mostrar" },
        { palabraSue: "Ge", palabraEsp: "Dar" },
        { palabraSue: "Förbereda", palabraEsp: "Preparar" },
        { palabraSue: "Rädda", palabraEsp: "Salvar" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Välja", palabraEsp: "Elegir" },
        { palabraSue: "Kasta", palabraEsp: "Tirar" },
        { palabraSue: "Komma", palabraEsp: "Venir" },
        { palabraSue: "Hitta", palabraEsp: "Encontrar" },
        { palabraSue: "Stå", palabraEsp: "Estar de pie" },
        { palabraSue: "Vänja", palabraEsp: "Acostumbrarse" },
        { palabraSue: "Börja", palabraEsp: "Comenzar" },
        { palabraSue: "Sluta", palabraEsp: "Dejar de" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Titta", palabraEsp: "Mirar" },
        { palabraSue: "Bara", palabraEsp: "Solo" },
        { palabraSue: "Använda", palabraEsp: "Usar" },
        { palabraSue: "Vänta", palabraEsp: "Esperar" },
        { palabraSue: "Kasta", palabraEsp: "Lanzar" },
        { palabraSue: "Skriva", palabraEsp: "Escribir" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Fråga", palabraEsp: "Preguntar" },
        { palabraSue: "Bygga", palabraEsp: "Construir" },
        { palabraSue: "Slå", palabraEsp: "Golpear" },
        { palabraSue: "Möta", palabraEsp: "Encontrar" },
        { palabraSue: "Få", palabraEsp: "Recibir" },
        { palabraSue: "Föreställa", palabraEsp: "Imaginar" },
        { palabraSue: "Vara", palabraEsp: "Ser" },
        { palabraSue: "Höra", palabraEsp: "Oír" },
        { palabraSue: "Föreslå", palabraEsp: "Sugerir" },
        { palabraSue: "Se", palabraEsp: "Ver" },
        { palabraSue: "Skratta", palabraEsp: "Reír" },
        { palabraSue: "Vänta", palabraEsp: "Esperar" },
        { palabraSue: "Använda", palabraEsp: "Usar" },
        { palabraSue: "Förlora", palabraEsp: "Perder" },
        { palabraSue: "Tänka", palabraEsp: "Pensar" },
        { palabraSue: "Läsa", palabraEsp: "Leer" },
        { palabraSue: "Tala", palabraEsp: "Hablar" },
        { palabraSue: "Arbeta", palabraEsp: "Trabajar" }    
    
  ],

    adjetivos : [
    { palabraSue: "Stor", palabraEsp: "Grande" },
    { palabraSue: "Liten", palabraEsp: "Pequeño" },
    { palabraSue: "Hög", palabraEsp: "Alto" },
    { palabraSue: "Låg", palabraEsp: "Bajo" },
    { palabraSue: "Vacker", palabraEsp: "Hermoso" },
    { palabraSue: "Fula", palabraEsp: "Feo" },
    { palabraSue: "Tung", palabraEsp: "Pesado" },
    { palabraSue: "Lätt", palabraEsp: "Ligero" },
    { palabraSue: "Bra", palabraEsp: "Bueno" },
    { palabraSue: "Dålig", palabraEsp: "Malo" },
    { palabraSue: "Snabb", palabraEsp: "Rápido" },
    { palabraSue: "Långsam", palabraEsp: "Lento" },
    { palabraSue: "Varm", palabraEsp: "Caliente" },
    { palabraSue: "Kall", palabraEsp: "Frío" },
    { palabraSue: "Ny", palabraEsp: "Nuevo" },
    { palabraSue: "Gammal", palabraEsp: "Viejo" },
    { palabraSue: "Ljus", palabraEsp: "Brillante" },
    { palabraSue: "Mörk", palabraEsp: "Oscuro" },
    { palabraSue: "Rik", palabraEsp: "Rico" },
    { palabraSue: "Fattig", palabraEsp: "Pobre" },
    { palabraSue: "Söt", palabraEsp: "Dulce" },
    { palabraSue: "Sur", palabraEsp: "Ácido" },
    { palabraSue: "Trött", palabraEsp: "Cansado" },
    { palabraSue: "Frisk", palabraEsp: "Sano" },
    { palabraSue: "Hälsosam", palabraEsp: "Saludable" },
    { palabraSue: "Trevlig", palabraEsp: "Agradable" },
    { palabraSue: "Tråkig", palabraEsp: "Aburrido" },
    { palabraSue: "Vänlig", palabraEsp: "Amistoso" },
    { palabraSue: "Otrevlig", palabraEsp: "Antipático" },
    { palabraSue: "Säker", palabraEsp: "Seguro" },
    { palabraSue: "Osäker", palabraEsp: "Inseguro" },
    { palabraSue: "Ren", palabraEsp: "Limpio" },
    { palabraSue: "Skräpig", palabraEsp: "Sucio" },
    { palabraSue: "Hög", palabraEsp: "Alto" },
    { palabraSue: "Låg", palabraEsp: "Bajo" },
    { palabraSue: "Trevlig", palabraEsp: "Amigable" },
    { palabraSue: "Arg", palabraEsp: "Enfadado" },
    { palabraSue: "Glad", palabraEsp: "Feliz" },
    { palabraSue: "Sorglig", palabraEsp: "Triste" },
    { palabraSue: "Kreativ", palabraEsp: "Creativo" },
    { palabraSue: "Tråkig", palabraEsp: "Aburrido" },
    { palabraSue: "Smart", palabraEsp: "Inteligente" },
    { palabraSue: "Dum", palabraEsp: "Tonto" },
    { palabraSue: "Lugn", palabraEsp: "Calmado" },
    { palabraSue: "Stressad", palabraEsp: "Estresado" },
    { palabraSue: "Vacker", palabraEsp: "Hermoso" },
    { palabraSue: "Fult", palabraEsp: "Feo" },
    { palabraSue: "Stark", palabraEsp: "Fuerte" },
    { palabraSue: "Svag", palabraEsp: "Débil" },
    { palabraSue: "Vänlig", palabraEsp: "Amistoso" },
    { palabraSue: "Otrevlig", palabraEsp: "Desagradable" },
    { palabraSue: "Trevlig", palabraEsp: "Amigable" },
    { palabraSue: "Snäll", palabraEsp: "Amable" },
    { palabraSue: "Elak", palabraEsp: "Malo" },
    { palabraSue: "Lugn", palabraEsp: "Tranquilo" },
    { palabraSue: "Orolig", palabraEsp: "Inquieto" },
    { palabraSue: "Intressant", palabraEsp: "Interesante" },
    { palabraSue: "Tråkig", palabraEsp: "Aburrido" },
    { palabraSue: "Mysig", palabraEsp: "Acogedor" },
    { palabraSue: "Kall", palabraEsp: "Frío" },
    { palabraSue: "Varm", palabraEsp: "Caliente" },
    { palabraSue: "Hård", palabraEsp: "Duro" },
    { palabraSue: "Mjuk", palabraEsp: "Blando" },
    { palabraSue: "Torr", palabraEsp: "Seco" },
    { palabraSue: "Fuktig", palabraEsp: "Húmedo" },
    { palabraSue: "Ljus", palabraEsp: "Claro" },
    { palabraSue: "Mörk", palabraEsp: "Oscuro" },
    { palabraSue: "Rund", palabraEsp: "Redondo" },
    { palabraSue: "Kantig", palabraEsp: "Cúbico" },
    { palabraSue: "Bred", palabraEsp: "Ancho" },
    { palabraSue: "Trång", palabraEsp: "Estrecho" },
    { palabraSue: "Tjock", palabraEsp: "Gordo" },
    { palabraSue: "Tunn", palabraEsp: "Delgado" },
    { palabraSue: "Hög", palabraEsp: "Alto" },
    { palabraSue: "Låg", palabraEsp: "Bajo" },
    { palabraSue: "Skadad", palabraEsp: "Dañado" },
    { palabraSue: "Frisk", palabraEsp: "Sano" },
    { palabraSue: "Skrattig", palabraEsp: "Divertido" },
    { palabraSue: "Mänsklig", palabraEsp: "Humano" },
    { palabraSue: "Oförutsägbar", palabraEsp: "Impredecible" },
    { palabraSue: "Förutsägbar", palabraEsp: "Predecible" },
    { palabraSue: "Speciell", palabraEsp: "Especial" },
    { palabraSue: "Vanlig", palabraEsp: "Común" },
    { palabraSue: "Öppen", palabraEsp: "Abierto" },
    { palabraSue: "Stängd", palabraEsp: "Cerrado" },
    { palabraSue: "Jämn", palabraEsp: "Suave" },
    { palabraSue: "Ojämn", palabraEsp: "Rugoso" },
    { palabraSue: "Trevliga", palabraEsp: "Agradables" },
    { palabraSue: "Nära", palabraEsp: "Cerca" },
    { palabraSue: "Långt", palabraEsp: "Lejos" },
    { palabraSue: "Blyg", palabraEsp: "Tímido" },
    { palabraSue: "Social", palabraEsp: "Sociable" },
    { palabraSue: "Skön", palabraEsp: "Cómodo" },
    { palabraSue: "Obekväm", palabraEsp: "Incómodo" },
    { palabraSue: "Perfekt", palabraEsp: "Perfecto" },
    { palabraSue: "Fel", palabraEsp: "Incorrecto" },
    { palabraSue: "Fantastisk", palabraEsp: "Fantástico" },
    { palabraSue: "Dålig", palabraEsp: "Malo" },
    { palabraSue: "Skrattig", palabraEsp: "Divertido" },
    { palabraSue: "Allvarlig", palabraEsp: "Serio" },
    { palabraSue: "Rolig", palabraEsp: "Divertido" },
    { palabraSue: "Konstig", palabraEsp: "Extraño" },
    { palabraSue: "Ursäkta", palabraEsp: "Disculpa" },
    { palabraSue: "Vänlig", palabraEsp: "Amigable" },
    { palabraSue: "Respektfull", palabraEsp: "Respetuoso" },
    { palabraSue: "Trevlig", palabraEsp: "Agradable" }
],


  palabrasImportantes: [
        { palabraSue: "Hej", palabraEsp: "Hola" },
        { palabraSue: "Tack", palabraEsp: "Gracias" },
        { palabraSue: "Ja", palabraEsp: "Sí" },
        { palabraSue: "Nej", palabraEsp: "No" },
        { palabraSue: "Snälla", palabraEsp: "Por favor" },
        { palabraSue: "Förlåt", palabraEsp: "Perdón" },
        { palabraSue: "Ursäkta", palabraEsp: "Disculpe" },
        { palabraSue: "God morgon", palabraEsp: "Buenos días" },
        { palabraSue: "God natt", palabraEsp: "Buenas noches" },
        { palabraSue: "Adjö", palabraEsp: "Adiós" },
        { palabraSue: "Vänligen", palabraEsp: "Amablemente" },
        { palabraSue: "Varför", palabraEsp: "Por qué" },
        { palabraSue: "Hur", palabraEsp: "Cómo" },
        { palabraSue: "När", palabraEsp: "Cuándo" },
        { palabraSue: "Var", palabraEsp: "Dónde" },
        { palabraSue: "Vad", palabraEsp: "Qué" },
        { palabraSue: "Vem", palabraEsp: "Quién" },
        { palabraSue: "Vilken", palabraEsp: "Cuál" },
        { palabraSue: "Och", palabraEsp: "Y" },
        { palabraSue: "Eller", palabraEsp: "O" },
        { palabraSue: "Men", palabraEsp: "Pero" },
        { palabraSue: "Så", palabraEsp: "Entonces" },
        { palabraSue: "Här", palabraEsp: "Aquí" },
        { palabraSue: "Där", palabraEsp: "Allí" },
        { palabraSue: "Alltid", palabraEsp: "Siempre" },
        { palabraSue: "Aldrig", palabraEsp: "Nunca" },
        { palabraSue: "Kanske", palabraEsp: "Quizás" },
        { palabraSue: "Redan", palabraEsp: "Ya" },
        { palabraSue: "Ofta", palabraEsp: "A menudo" },
        { palabraSue: "Sällan", palabraEsp: "Rara vez" },
        // ... Añade más palabras importantes hasta llegar a 300
      ]
      
};

// Función para obtener palabras según la categoría
const obtenerPalabras = async (categoria) => {
  try {
    // Simulación de llamada a una API con un pequeño retraso
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(vocabulario[categoria] || []);
      }, 1500); // 0.5 segundos de retraso para simular la carga
    });
  } catch (error) {
    console.error("Error al obtener palabras:", error);
    throw error;
  }
};

export default obtenerPalabras;
